package github

// GitHub hook types.
const (
	ForkEvent                                Event = "fork"
	MetaEvent                                Event = "meta"
	TeamEvent                                Event = "team"
	PingEvent                                Event = "ping"
	PushEvent                                Event = "push"
	LabelEvent                               Event = "label"
	WatchEvent                               Event = "watch"
	CreateEvent                              Event = "create"
	DeleteEvent                              Event = "delete"
	GollumEvent                              Event = "gollum"
	PublicEvent                              Event = "public"
	IssuesEvent                              Event = "issues"
	MemberEvent                              Event = "member"
	StatusEvent                              Event = "status"
	ProjectEvent                             Event = "project"
	ReleaseEvent                             Event = "release"
	TeamAddEvent                             Event = "team_add"
	OrgBlockEvent                            Event = "org_block"
	CheckRunEvent                            Event = "check_run"
	DeployKeyEvent                           Event = "deploy_key"
	MilestoneEvent                           Event = "milestone"
	PageBuildEvent                           Event = "page_build"
	CheckSuiteEvent                          Event = "check_suite"
	DeploymentEvent                          Event = "deployment"
	RepositoryEvent                          Event = "repository"
	MembershipEvent                          Event = "membership"
	PullRequestEvent                         Event = "pull_request"
	ProjectCardEvent                         Event = "project_card"
	WorkflowJobEvent                         Event = "workflow_job"
	WorkflowRunEvent                         Event = "workflow_run"
	OrganizationEvent                        Event = "organization"
	IssueCommentEvent                        Event = "issue_comment"
	InstallationEvent                        Event = "installation"
	CommitCommentEvent                       Event = "commit_comment"
	ProjectColumnEvent                       Event = "project_column"
	DependabotAlertEvent                     Event = "dependabot_alert"
	DeploymentStatusEvent                    Event = "deployment_status"
	SecurityAdvisoryEvent                    Event = "security_advisory"
	WorkflowDispatchEvent                    Event = "workflow_dispatch"
	CodeScanningAlertEvent                   Event = "code_scanning_alert"
	PullRequestReviewEvent                   Event = "pull_request_review"
	GitHubAppAuthorizationEvent              Event = "github_app_authorization"
	IntegrationInstallationEvent             Event = "integration_installation"
	PullRequestReviewCommentEvent            Event = "pull_request_review_comment"
	InstallationRepositoriesEvent            Event = "installation_repositories"
	RepositoryVulnerabilityAlertEvent        Event = "repository_vulnerability_alert"
	IntegrationInstallationRepositoriesEvent Event = "integration_installation_repositories"
)


// Event defines a GitHub hook event type.
type Event string
